### ISSUE TITLE
Errors in ROds macros in macros.h

### ISSUE THREAD

**Issue by anodynesoftware** [freemint/mintlib#10]
Many of the rotate macros generate incorrect assembler instructions. For example,
#define RORL1(x)	\
({ unsigned long __arg = (x);	\
    __asm__ ("roll #1,%1": "=d" (__arg) : "0" (__arg)); \
    __arg; })

generates a rol.l instruction instead of an ror.l instruction. Other rotate macros use the wrong width as well.

**Comment by mikrosk** [comment]
Just to clarify, we're talking about this file: https://github.com/freemint/mintlib/blob/master/include/macros.h

and indeed some things look really wrong. I wonder if at least the size problem doesn't go away if the final size is correct, like:

```
#define ROLB1(x)	\
({ unsigned char __arg = (x);	\
    __asm__ ("roll #1,%1": "=d" (__arg) : "0" (__arg)); \
    __arg; })
```
