### ISSUE TITLE
Wrong definition of pun_ptr

### ISSUE THREAD

**Issue by czietz** [freemint/mintlib#43]
In mint/sysvars.h, `pun_ptr` is declared as follows:
https://github.com/freemint/mintlib/blob/42c99b60bf8a8fc111ed0290071d540fc92da93f/include/mint/sysvars.h#L98

This is missing one level of indirection, as it should be...
```
#define pun_ptr	((HDINFO **) 0x516L)
```

As it is currently, it says that a HDINFO structure resides at address 0x516. But in fact it is a _pointer_ to the structure that is at address 0x516. The difference is exemplified by this small sample program:
https://tinyurl.com/yyg8lh23
Notice how in the error case `pstart[2]` is retrieved from address 0x530 (1328.w), which is wrong.

**Comment by th-otto** [comment]
On Dienstag, 12. Januar 2021 22:32:22 CET Christian Zietz wrote:
> In mint/sysvars.h, `pun_ptr` is declared as follows:

Thanks for spotting this. Should be fixed now.

**Comment by czietz** [comment]
Thank you.
