### ISSUE TITLE
basename() doesn't work

### ISSUE THREAD

**Issue by xdelatour** [freemint/mintlib#46]
basename() doesn't work as expected.

Steps to reproduce :
```
#include <stdio.h>
#include <libgen.h>
int main(void)
{
	printf ("name=%s\n", basename("/some/directory/and/thebasefilename"));
	return 0;
}
```
Output (Linux)
```
name=thebasefilename
```
Ouput (FreeMiNT)
```
name=/thebasefilename
```

The else statement (to skip the first '/') is missing in [xpg_basename.c](https://github.com/freemint/mintlib/blob/d7069179af01be773d478f1305e72f8e81569c81/stdlib/xpg_basename.c). Original file can be found [there](https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/stdlib/xpg_basename.c).

The patch adds the following lines:
```
} else {
	/* Go to the first character of the name.  */
	++p;
```
[xpg_basename.patch.txt](https://github.com/freemint/mintlib/files/9388533/xpg_basename.patch.txt)

**Comment by th-otto** [comment]
Dooh. That file is still the first version ever committed, and has never been changed. Wonder why nobody ever noticed this.

But note that there is also a version in string/basename.c, and that works.

Should be fixed now.
