### ISSUE TITLE
Linking with -liio does not always work as intended

### ISSUE THREAD

**Issue by th-otto** [freemint/mintlib#52]
When linking with -liio (in order to prevent linking in floating point functions) sometimes the normal scanf() function from libc is still linked in. That has the undesired effect that for example strtod() (see also https://github.com/freemint/mintlib/issues/51)  is also linked in.

To reproduce use something like:
```
#include <stdio.h>

char buf[100];

int main(void)
{
        sscanf(buf, "%s", buf);
        printf("%s\n", buf);
        return 0;
}
```

Then compile with ``m68k-atari-mint-gcc -O foo.c -liio -Wl,-Map,foo.map``

Then do ``grep strtod`` foo.map to check that it was linked in.

I think one of the reasons is that sscanf.o is missing from the library, and how the linker works. Since sscanf is missing from libiio.o, the linker will not consider it, and use one from libc instead, which in turn links in other functions.

At least that is what i found so far. There might be other functions missing, too. There might also be some issue with weak symbols (the vfscanf function is internally declared as __vfscanf, with a weak symbol for vfscanf; for the printf() family of functions this is not done). And there are places where that internal function is called directly, instead of the publicitly available function.

**Comment by mikrosk** [comment]
Wow, thumbs up even for taking a look what that libiio is doing, I've been wondering about that for a long time.

Unfortunately, this is completely alien to me, can't help or even have an opinion. :)

**Comment by mikrosk** [comment]
I think ending with an error is better as it makes clear that something is really wrong and it should be fixed. 

As I see, there's a lot of interesting tasks left.

**Comment by th-otto** [comment]
BTW i recently pushed a fix for that. Hope i didn't miss anything.

The  idea about abort() ing isn't implemented yet.
