### ISSUE TITLE
GCC 13 wants to fix features.h

### ISSUE THREAD

**Issue by vinriviere** [freemint/mintlib#62]
Seen there: https://github.com/freemint/m68k-atari-mint-gcc/issues/29
GCC 13 fixincludes want to fix features.h:

```
$ diff -u /usr/m68k-atari-mintelf/include/features.h /usr/lib/gcc/m68k-atari-mintelf/13.2.0/include-fixed/features.h
@@ -507,7 +516,7 @@
 
 /* Decide whether we can define 'extern inline' functions in headers.  */
 #if __GNUC_PREREQ (2, 7) && defined __OPTIMIZE__ \
-    && !defined __OPTIMIZE_SIZE__ && !defined __NO_INLINE__
+    && !defined __OPTIMIZE_SIZE__ && !defined __NO_INLINE__ && (defined __extern_inline || defined __GNUC_GNU_INLINE__)
 # define __USE_EXTERN_INLINES	1
 # if (defined __GNUC_STDC_INLINE__ && __GNUC_STDC_INLINE__) || \
      defined __cplusplus || \
```

Is this relevant?
Do we need to definitely fix MiNTLib's features.h that way? Or differently?

**Comment by th-otto** [comment]
I rather don't want to change that. We had already different issues with the definition of inline in the past. And those header must work also with older compilers.

Maybe better try to find the pattern that causes fixincludes to "fix" this file, and avoid it being fixed.

**Comment by th-otto** [comment]
>Don't forget that this include fixing drags with it also a bunch of external library headers, even Linux ones.

I don't get linux ones in there (i think we had that discussed already somewhere), but headers that i've installed from other cross-compiled packages. Eg. `<SDL/SDL_endian.h>` is also fixed (IIRC, because it uses `mc68000` instead of `__mc68000__`)

>So why picking up this one particular features.h ? Just use --disable-fixincludes.

Maybe that would also be an option. But until Vincent has also changed his script, it's imho safer to just ensure that features.h does not end up there.

**Comment by mikrosk** [comment]
Fortunately it's not so many of us providing gcc executables. ;) I just wanted to avoid a situation where we have a wave of commits in various projects adding spaces to fool gcc, that's all.
