### ISSUE TITLE
GCC 13 wants to fix bits/string2.h

### ISSUE THREAD

**Issue by vinriviere** [freemint/mintlib#63]
Seen there: https://github.com/freemint/m68k-atari-mint-gcc/issues/29
GCC 13 fixincludes want to fix bits/string2.h:

```
$ diff -u /usr/m68k-atari-mintelf/include/bits/string2.h /usr/lib/gcc/m68k-atari-mintelf/13.2.0/include-fixed/bits/string2.h
@@ -544,22 +553,9 @@
 /* Copy no more than N characters of SRC to DEST.  */
 #ifndef _HAVE_STRING_ARCH_strncpy
 # if defined _HAVE_STRING_ARCH_memset && defined _HAVE_STRING_ARCH_mempcpy
-#  define strncpy(dest, src, n) \
-  (__extension__ ({ char *__dest = (dest);				      \
-		    __builtin_constant_p (src) && __builtin_constant_p (n)    \
-		    ? (strlen (src) + 1 >= ((size_t) (n))		      \
-		       ? (char *) memcpy (__dest, src, n)		      \
-		       : (memset (__mempcpy (__dest, src, strlen (src)),      \
-				  '\0', n - strlen (src)),		      \
-			  __dest))					      \
-		    : strncpy (__dest, src, n); }))
+#  define strncpy(dest, src, n) __builtin_strncpy (dest, src, n)
 # else
-#  define strncpy(dest, src, n) \
-  (__extension__ (__builtin_constant_p (src) && __builtin_constant_p (n)      \
-		  ? (strlen (src) + 1 >= ((size_t) (n))			      \
-		     ? (char *) memcpy (dest, src, n)			      \
-		     : strncpy (dest, src, n))				      \
-		  : strncpy (dest, src, n)))
+#  define strncpy(dest, src, n) __builtin_strncpy (dest, src, n)
 # endif
 #endif
```

Is this relevant?
Do we need to definitely fix MiNTLib's bits/string2.h that way? Or differently?

**Comment by th-otto** [comment]
As already mentioned, we could fix it whatever gcc thinks it should be fixed, because it is not actually used (the include in <string.h> is ifdef'd out)

But if we keep it, it should also be checked with other gcc versions. They might "fix" it in a different way. Otherwise just remove that file from mintlib, or at least don't install it.

**Comment by vinriviere** [comment]
> As already mentioned, we could fix it whatever gcc thinks it should be fixed, because it is not actually used (the include in <string.h> is ifdef'd out)

Ah. Indeed.
https://github.com/freemint/mintlib/blob/b77a680f1c944f587b9380e6c007814e6f81b0cd/include/string.h#L320-L359

> But if we keep it, it should also be checked with other gcc versions. They might "fix" it in a different way. Otherwise just remove that file from mintlib, or at least don't install it.

So I would say, let's remove all that unused stuff from the MiNTLib. Generally, dead code is considered as bad practice. And if for any reason we want to revive that code, we can still recover it from Git history.

**Comment by th-otto** [comment]
Fixed with https://github.com/freemint/mintlib/commit/fe48911ce092361ba014df65664256b45dcecbe2
