### ISSUE TITLE
futimes() produces bogus date on ARAnyM's hostfs

### ISSUE THREAD

**Issue by vinriviere** [freemint/mintlib#65]
I've just recompiled tar 1.35. It uses `futimes()` after extracting an archive in order to restore the original file times.

There is a general issue about inversion on access/modification times. I opened #64 specifically for that one, different from the current issue.

When the files are extracted on ARAnyM+hostfs, the resulting dates are bogus. I.e. my archive contains a file with modification date 05/08/2023. After extraction on hostfs, the access/modify dates are bogus (namely, 1916 and 1952).

I use the an up-to-date kernel and the ARAnyM version shipped with Ubuntu 23.10 "Mantic Minotaur". It says to be ARAnyM 1.1.0.

I'm not sure if that's a MiNTLib, FreeMiNT or ARAnyM bug. I see there are multiple fallbacks in the code.

For reference:

MiNTLib's futimes():
https://github.com/freemint/mintlib/blob/b77a680f1c944f587b9380e6c007814e6f81b0cd/unix/futimes.c

FreeMiNT's FUTIME:
https://github.com/freemint/freemint/blob/287b69264ee230a5a6b62d399ecc17e1cf91377b/sys/dosfile.c#L594-L609

**Comment by vinriviere** [comment]
@th-otto I've fixed #64. Do you plan to have a look at this one?

**Comment by th-otto** [comment]
That was a mismatch between the timestamp format used by the  kernel and aranym, and should be fixed by https://github.com/aranym/aranym/commit/e433eaeea43fdd8276ddd17fcdb17a652c1d4747

Could you retest with a current version of aranym?

**Comment by vinriviere** [comment]
> Could you retest with a current version of aranym?

I would like to do, but it seems that the snapshots website is no more available:
https://bintray.com/aranym/aranym-files/snapshots

Is it possible to download current ARAnyM snapshots somewhere else?

BTW, you can also easily test yourself with the testcase I posted on #64.

**Comment by vinriviere** [comment]
I finally managed to build ARAnyM myself for Cygwin.

Thanks @th-otto, it works. Problem fixed.
