### ISSUE TITLE
Problem when compiling mintlib without optimizations

### ISSUE THREAD

**Issue by th-otto** [freemint/mintlib#67]
There is a problem in the startup code when compiling mintlib with debug setting (wasn't done for now because gdb wasn't available, but now it is for elf toolchains)

In https://github.com/freemint/mintlib/blob/dca328840d8bafc91a913356a0a752f6642d1e7e/mintlib/crtinit.c#L195-L199

the stackpointer is changed, and afterwards the Mshrink() call uses bp (a local variable). When compiling without optimization, bp will not be in a register, but on the old stack. Since the stackpointer already was changed, that will access a wrong offset. Also, debug code typically uses the framepointer (a6), but setstack only adjusts the a7.

I first thought of just reordering the calls (doing the Mshrink first), but then we get another problem when using MP: the call to setstack() will push the argument on a stack that is no longer writable, because Mshrink() changed the protection tables.

I can only think of fixing that by putting the two calls into inline assembly that does the right thing. Any better ideas?

**Comment by mikrosk** [comment]
Making it an inline assembly seems like the safest option to me.

Good catch!

**Comment by th-otto** [comment]
Should be fixed by https://github.com/freemint/mintlib/commit/5f0a5ec18a6d69e0b84e9170cda7e0e2e3b7732a

**Comment by mikrosk** [comment]
Nice  one, thanks Thorsten.
