### ISSUE TITLE
clock_gettime missing

### ISSUE THREAD

**Issue by MedourMehdi** [freemint/mintlib#74]
Hi,

If you think the code attached correct may it will be possible to implement clock_gettime in mintlib?
The archive contains the header & c code plus a simple clock_gettime() test.

To build the example on osx/linux I used: gcc clock_test.c -o clock_gettime_osx
To build it for mint I used: m68k-atari-mint-gcc clock_gettime.c clock_test.c -o clock_gettime_mint

Results are the same on osx and mint (check screenshot below).

[clock_gettime_mint.zip](https://github.com/user-attachments/files/16475591/clock_gettime_mint.zip)

<img width="1250" alt="Capture d’écran 2024-08-02 à 23 31 50" src="https://github.com/user-attachments/assets/7799600b-b074-4e5c-b359-5c8673f6c748">

**Comment by mikrosk** [comment]
Fixed by #77 77.
