### ISSUE TITLE
strndup implementation broken?

### ISSUE THREAD

**Issue by MedourMehdi** [freemint/mintlib#78]
Hi,

What is wrong with this function in the mintlib?

This simple example doesn't work.

```
// C program to demonstrate strndup()
#include<stdio.h>
#include<string.h>

int main()
{
        const char source[] = "GeeksForGeeks";
        const char str[] = "How many characters does this string contain?";

        printf("without null character: %zu\n", strlen(str));
        printf("with null character:    %zu\n", sizeof str);

        char* target = strndup(source, 5);

        printf("%s", target);
        return 0;
}
```
<img width="796" alt="Capture d’écran 2024-09-07 à 17 55 27" src="https://github.com/user-attachments/assets/b4a05b89-bf7f-402e-9bf6-e54bbd433f63">

Am I missing something?

**Comment by vinriviere** [comment]
"implicit declaration of function" means that the prototype is missing. Answer is here:
https://github.com/freemint/mintlib/blob/059189ca233d345fc85d628f8f6c62b2474a05bb/include/string.h#L93-L95

The solution is to compile with `-D_GNU_SOURCE` to enable the internal `__USE_GNU` flag, and actually enable the `strndup()` prototype.

**Comment by MedourMehdi** [comment]
I was trying with -D__USE_GNU but without success.
Many thanks Vincent. I don't know if using defines for this kind of function is relevant. 
Whatever it solved the build.
